# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# XDG Desktop Portal
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Wallpaper
exec-once = awww-daemon
exec-once = awww img ~/wallpapers/main.png

# Status bar
exec-once = waybar

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Notifications
exec-once = dunst

# Brightness daemon (software gamma dim)
exec-once = wl-gammarelay-rs
exec-once = /home/lynx/.local/bin/brightness restore

#cliphist
exec-once = cliphist wipe
