background {
    path = ~/wallpapers/lock.png
    blur_passes = 3
    blur_size = 8
}

input-field {
    size = 250, 50
    outline_thickness = 2
    outer_color = rgba(137, 180, 250, 0.4)
    inner_color = rgba(30, 30, 46, 0.9)
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}
