# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -show-icons
$browser = firefox

$mainMod = SUPER # Sets "Windows" key as main modifier
